<footer>
    <p>&copy; 2025 Meow Meows Inc. All rights reserved. | Bringing digital purr-fection to life.</p>

    <a href="terms.html">Terms & Conditions</a> 
    <a href="privacy.html">Privacy Policy</a> 

    <!-- Repository and project-management links -->
    <p>
        <a href="https://github.com/RoryNorbury/COS10026-Project-Part-1" target="_blank">
            Project GitHub Repository
        </a>
    </p>
    <p>
        <a href="https://meowmeowscos10026.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiOTM3NzdlOTMyMjkzNDNlNTgxMzkzMTNmMjFkZWM3MGEiLCJwIjoiaiJ9" target="_blank">
            Jira Project Board
        </a>
    </p>
</footer>
</html>
